# Generated by Django 4.0 on 2022-02-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0001_create_organization_unit_employee_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='unit',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='employees',
            field=models.ManyToManyField(blank=True, to='organization.Employee'),
        ),
    ]
